### ISSUE TITLE
Does not work on Gnome 3.28.x

### ISSUE THREAD

**Issue by avrahamshukron** [koolskateguy89/gnome-shell-extension-spotify-controller#3]
Cannot enable the extension under Gnome 3.28.
When trying to open the settings dialog I get the following error:
```
TypeError: ExtensionUtils.getSettings is not a function

Stack trace:
  buildPrefsWidget@/home/ANT.AMAZON.COM/ashukro/.local/share/gnome-shell/extensions/spotify-controller@koolskateguy89/prefs.js:13:20
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```

**Comment by koolskateguy89** [comment]
Thanks for letting me know, I'll work on it

**Comment by koolskateguy89** [comment]
@avrahamshukron I think I've fixed it, can you please re-install the extension with [this zip folder](https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/files/6079536/spotify-controller%40koolskateguy89.zip).

If you don't know how to do it:

- Uninstall your current version of the extension:
`rm -r ~/.local/share/gnome-shell/extensions/spotify-controller@koolskateguy89`
- Download the zip folder
`wget https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/files/6079536/spotify-controller%40koolskateguy89.zip`
- Extract it into ~/.local/share/gnome-shell/extensions/spotify-controller@koolskateguy89
`unzip spotify-controller@koolskateguy89.zip -d ~/.local/share/gnome-shell/extensionsspotify-controller@koolskateguy89`

**Comment by koolskateguy89** [comment]
I'm gonna add this to the main version of the extension actually as it's less version dependant

**Comment by avrahamshukron** [comment]
@koolskateguy89 Thank you for the quick response!
Your change made it so I can open the settings dialog, but the extension still fails to load.

I don't know how to provide more info...
When trying to enable through the Gnome Tweaks GUI, I get an error "extension failed to load" with no further logs or info.

Interestingly - enabling it through the command line using `gnome-shell-extension-tool -e spotify-controller@koolskateguy89` "works", but the extension still doesn't show in the top bar.

Hope that helps.

I would upgrade my Gnome a long time ago, but it is actually a company-managed laptop so I can't.

**Comment by koolskateguy89** [comment]
@avrahamshukron Happy to help!

For more debug info:
Please run the command `journalctl /usr/bin/gnome-shell -f -o cat` then restart GNOME Shell (Alt+F2 then type r).
Then:
- Copy the output and paste into a text editor (stop the command with Ctrl+C first)
- Search/find "spotify"
- You should see something like 
`JS ERROR: Extension spotify-controller@koolskateguy89: ......`

Can you please copy the entire paragraph(s) containing this and paste it here, thank you.

Unfortunately I can't change to Gnome 3.28 to try and fix it myself :/

**Comment by avrahamshukron** [comment]
The only relevant line that I could find that directly referenced "spotify" was:
```
Extension "spotify-controller@koolskateguy89" had error: TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)
```

**Comment by koolskateguy89** [comment]
I see, I think I know how to fix this - should be done soon

**Comment by koolskateguy89** [comment]
@avrahamshukron Can you please try it again with [this zip file](https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/files/6083806/spotify-controller%40koolskateguy89.zip) as the extension?

**Comment by koolskateguy89** [comment]
Wait no nevermind I found a way to break it, give me some more time

**Comment by koolskateguy89** [comment]
@avrahamshukron Please try with [this zip file](https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/files/6083866/spotify-controller%40koolskateguy89.zip)

`wget https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/files/6083866/spotify-controller%40koolskateguy89.zip` etc.)

**Comment by avrahamshukron** [comment]
Next error:
```
Extension "spotify-controller@koolskateguy89" had error: TypeError: this.add_child is not a function
```
Eventually we'll get there :laughing:

**Comment by koolskateguy89** [comment]
Would it be possible for you to paste the entire paragraph? So I can see the entire trace?

**Comment by avrahamshukron** [comment]
There is none. I would have paste it if there was more info.

I'm posting the output of the `journalctl` command, maybe you'll find something useful:

```
journalctl /usr/bin/gnome-shell -f -o cat[AppIndicatorSupport-FATAL] unable to lookup icon for Slack1_144                        
[AppIndicatorSupport-FATAL] unable to lookup icon for Slack1_146                                                                                                          
[AppIndicatorSupport-FATAL] unable to lookup icon for Slack1_146                                                                                                          
Fontconfig error: Cannot load default config file: No such file: (null)                                                                                                   
[AppIndicatorSupport-FATAL] unable to lookup icon for Slack1_147                                                                                                          
[AppIndicatorSupport-FATAL] unable to lookup icon for Slack1_147                                                                                                          
[AppIndicatorSupport-FATAL] unable to lookup icon for Slack1_148                                                                                                          
[AppIndicatorSupport-FATAL] unable to lookup icon for Slack1_148                                                                                                          
[AppIndicatorSupport-FATAL] unable to lookup icon for Slack1_148                                                                                                          
Gtk-Message: 13:19:30.333: GtkDialog mapped without a transient parent. This is discouraged.                                                                              
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.                                                                         
JS ERROR: TypeError: this._trackedWindows.get(...) is undefined                                                                                                           
_onWindowActorRemoved@resource:///org/gnome/shell/ui/panel.js:836:9                                                                                                       
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22                                                                                                                
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:206:9                                                                                                              
                                                                                                                                                                          
current session already has an ibus-daemon.                                                                                                                               
Telepathy is not available, chat integration will be disabled.                                                                                                            
Some code accessed the property 'SoundDeviceChooserBase' on the module 'base'. That property was defined with 'let' or 'const' inside the module. This was previously supp
orted, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously 
for the time being, but please fix your code anyway.                                                                                                                      
Some code accessed the property 'SETTINGS_SCHEMA' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported,
 but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for th
e time being, but please fix your code anyway.                                                                                                                            
JS WARNING: [/home/ANT.AMAZON.COM/ashukro/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js 200]: reference to undefined property
 Symbol.toPrimitive                                                                                                                                                       
Some code accessed the property 'SHOW_INPUT_SLIDER' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supporte
d, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for 
the time being, but please fix your code anyway.                                                                                                                          
Extension "spotify-controller@koolskateguy89" had error: TypeError: this.add_child is not a function                                                                      
Some code accessed the property 'ScrollablePopupMenu' on the module 'scrollablePopupMenu'. That property was defined with 'let' or 'const' inside the module. This was pre
viously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as
 previously for the time being, but please fix your code anyway.                                                                                                          
Some code accessed the property 'PopupExtensionItem' on the module 'popupExtensionItem'. That property was defined with 'let' or 'const' inside the module. This was previ
ously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as p
reviously for the time being, but please fix your code anyway.                                                                                                            
JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1028]: unreachable code after return statement                                          
JS WARNING: [resource:///org/gnome/shell/ui/status/keyboard.js 723]: reference to undefined property "_inputSources"                                                      
[AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.99/org/ayatana/NotificationItem/Slack1                                                                      
[AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.79/org/ayatana/NotificationItem/livepatch                                                                   
[AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.54/org/ayatana/NotificationItem/uquarantine                                                                 
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation                                                                  
gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed                                                                                                     
Some code accessed the property 'HIDE_ON_SINGLE_DEVICE' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supp
orted, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously 
for the time being, but please fix your code anyway.                                                                                                                      
Some code accessed the property 'SHOW_PROFILES' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, b
ut is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the 
time being, but please fix your code anyway.                                                                                                                              
Some code accessed the property 'ICON_THEME' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but 
is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the tim
e being, but please fix your code anyway.                                                                                                                                 
Some code accessed the property 'HIDE_MENU_ICONS' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported,
 but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for th
e time being, but please fix your code anyway.                                                                                                                            
Some code accessed the property 'PORT_SETTINGS' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, b
ut is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the 
time being, but please fix your code anyway.                                                                                                                              
Some code accessed the property 'SHOW_OUTPUT_DEVICES' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously suppor
ted, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously fo
r the time being, but please fix your code anyway.
```

**Comment by koolskateguy89** [comment]
I see, thank you, whenever I get an error it shows the entire error trace incl. what line it's from - must be due to different Shell versions.

Hopefully [this zip file](https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/files/6083981/spotify-controller%40koolskateguy89.zip) will solve all our problems

(link if you want to use `wget` or similar: 
https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/files/6083981/spotify-controller%40koolskateguy89.zip
)

**Comment by avrahamshukron** [comment]
It's working! Thank you so much!

**Comment by koolskateguy89** [comment]
Ayyyy let's go, happy to help
